id: A32168102
title: A Simple Method of Transference for Helpless Animals
type: translation
pechas:
- I22484F84
- IE14ACBF6
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:50:38.750337
  last_modified_at: 2023-01-04 11:50:38.750349
  collections:
  - Dzong-ngön Pema Tukchok Dorje
  - Works of Tibetan Masters
alignment_to_base:
  I22484F84/AFD7: 704D
  IE14ACBF6/4FFE: 704D
